from .base_page import BasePage
from .main_page import MainPage
from .options_page import OptionsPage
from .form_page import FormPage
from .elements_page import ElementsPage
from .buttons_page import ButtonsPage
from .links_page import LinksPage
from .dynamic_properties_page import DynamicPropertiesPage
from .widgets_page import WidgetsPage
from .slider_page import SliderPage
from .tabs_page import TabsPage
from .progress_bar_page import ProgressBarPage
from .alerts_windows_page import AlertsWindowsPage
from .alerts_page import AlertsPage
